# Generated by Django 4.1 on 2023-01-22 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255)),
                ('classname', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('available_times', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
    ]
