# Generated by Django 4.1 on 2023-01-22 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='teacher_name',
            field=models.CharField(default='s', max_length=255),
            preserve_default=False,
        ),
    ]
