# Generated by Django 4.1 on 2023-01-23 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_class_teacher_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='class',
            name='price',
            field=models.CharField(default='s', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='class',
            name='teacher_email',
            field=models.CharField(default='s@s.com', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
