# Generated by Django 4.1 on 2023-01-24 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_is_student_user_is_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='students',
            field=models.TextField(blank=True, default=''),
        ),
    ]
